# Generated by Django 3.2.6 on 2021-08-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('identity_type', models.CharField(choices=[('Adhr', 'Aadhaar'), ('Pn', 'Pan'), ('DL', 'Driving License'), ('Pp', 'Passport')], default='Aadhaar', max_length=20)),
                ('identity_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StoresList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_code', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=20)),
                ('manager', models.CharField(max_length=20)),
                ('contact_no', models.CharField(max_length=10)),
                ('manager_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WorkersDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=10)),
                ('mobile_number', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('identity_type', models.CharField(choices=[('Adhr', 'Aadhaar'), ('Pn', 'Pan'), ('DL', 'Driving License'), ('Pp', 'Passport')], default='Aadhaar', max_length=20)),
                ('identity_number', models.CharField(max_length=20)),
            ],
        ),
    ]
