# Generated by Django 3.2.6 on 2021-08-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strawsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=20)),
                ('items', models.TextField()),
                ('total_amount', models.IntegerField()),
            ],
        ),
    ]
