# Generated by Django 3.2.6 on 2021-08-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strawsapp', '0005_tableshistorydatabase'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableForm10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=20)),
                ('items', models.TextField()),
                ('total_amount', models.IntegerField()),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card Payment', 'Card Payment')], default='Cash', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TableForm4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=20)),
                ('items', models.TextField()),
                ('total_amount', models.IntegerField()),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card Payment', 'Card Payment')], default='Cash', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TableForm5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=20)),
                ('items', models.TextField()),
                ('total_amount', models.IntegerField()),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card Payment', 'Card Payment')], default='Cash', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TableForm6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=20)),
                ('items', models.TextField()),
                ('total_amount', models.IntegerField()),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card Payment', 'Card Payment')], default='Cash', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TableForm7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=20)),
                ('items', models.TextField()),
                ('total_amount', models.IntegerField()),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card Payment', 'Card Payment')], default='Cash', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TableForm8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=20)),
                ('items', models.TextField()),
                ('total_amount', models.IntegerField()),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card Payment', 'Card Payment')], default='Cash', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TableForm9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=20)),
                ('items', models.TextField()),
                ('total_amount', models.IntegerField()),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card Payment', 'Card Payment')], default='Cash', max_length=50)),
            ],
        ),
    ]
